/* ────────────────────────────────────────────────────────────────────────────
 * CalculationTracePanel
 *
 * The Calculation Trace modal. Renders the read-only trace generated by
 * `useCalculationTrace` with:
 *   • final-result header (with existing status / cycle warnings)
 *   • search within the trace
 *   • three display levels: Basic / Detailed (default) / Audit
 *   • collapsible steps (final result + check nodes expanded by default)
 *   • "Locate" per step → close panel, pan/zoom + highlight on the canvas
 *   • Markdown export reusing the existing report (Markdown + Blob) pattern
 *
 * UI states: loading, empty, success, warning (cycle), error, large trace,
 * no formula, no result. All theming follows the existing app palettes.
 * ──────────────────────────────────────────────────────────────────────────── */

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { CanvasNode, Connection, Theme } from '../../../types';
import ModalWindow from '../../../components/ModalWindow';
import { useCalculationTrace } from '../hooks/useCalculationTrace';
import { buildTraceMarkdown, searchTraceSteps } from '../services/calculationTraceService';
import type { FormulaProvider, TraceLevel } from '../types/calculationTrace.types';
import CalculationTraceHeader from './CalculationTraceHeader';
import CalculationTraceSearch from './CalculationTraceSearch';
import CalculationTraceStep, { type TraceColors } from './CalculationTraceStep';

interface Props {
  isOpen: boolean;
  theme: Theme;
  nodes: CanvasNode[];
  connections: Connection[];
  rootNodeId: string | null;
  formulaProvider?: FormulaProvider;
  projectName?: string;
  onClose: () => void;
  onLocateNode: (nodeId: string) => void;
}

const themeStyles: Record<Theme, TraceColors> = {
  dark:        { bg:'#1e293b',text:'#e2e8f0',border:'#334155',input:'#0f172a',label:'#94a3b8',accent:'#3b82f6',card:'#0f172a' },
  light:       { bg:'#ffffff',text:'#1e293b',border:'#e2e8f0',input:'#f1f5f9',label:'#64748b',accent:'#3b82f6',card:'#f8fafc' },
  grasshopper: { bg:'#2d3748',text:'#e2e8f0',border:'#4a5568',input:'#1a202c',label:'#a0aec0',accent:'#68d391',card:'#1a202c' },
  autocad:     { bg:'#1a1a1a',text:'#ffffff',border:'#333333',input:'#0a0a0a',label:'#888888',accent:'#00ff00',card:'#0a0a0a' },
};

const LEVELS: { id: TraceLevel; label: string }[] = [
  { id: 'basic', label: 'Basic' },
  { id: 'detailed', label: 'Detailed' },
  { id: 'audit', label: 'Audit' },
];

const LARGE_TRACE_THRESHOLD = 60;

export default function CalculationTracePanel({
  isOpen, theme, nodes, connections, rootNodeId, formulaProvider, projectName, onClose, onLocateNode,
}: Props) {
  const colors = themeStyles[theme];

  const { trace, error } = useCalculationTrace(nodes, connections, rootNodeId, isOpen, {
    formulaProvider,
  });

  const [level, setLevel] = useState<TraceLevel>('detailed');
  const [expanded, setExpanded] = useState<Record<string, boolean>>({});
  const [searchQuery, setSearchQuery] = useState('');
  const [flashId, setFlashId] = useState<string | null>(null);
  const searchInputRef = useRef<HTMLInputElement | null>(null);
  const stepRefs = useRef(new Map<string, HTMLDivElement>());
  const flashTimer = useRef<number | null>(null);

  /* ── Reset transient UI state each time a new node is traced ── */
  useEffect(() => {
    setSearchQuery('');
    setFlashId(null);
    if (trace) {
      setExpanded(Object.fromEntries(
        trace.steps.map(s => [
          s.id,
          // Final result and existing check/status nodes expanded by default;
          // intermediate nodes collapsed.
          s.isRoot || Boolean(s.status),
        ]),
      ));
    }
    // Re-run only when the traced root changes (not on every graph tick).
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [rootNodeId]);

  /* ── Accessibility: ESC closes, focus goes to the panel on open ── */
  useEffect(() => {
    if (!isOpen) return;
    const t = window.setTimeout(() => searchInputRef.current?.focus(), 50);
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', onKey);
    return () => {
      window.clearTimeout(t);
      window.removeEventListener('keydown', onKey);
    };
  }, [isOpen, onClose]);

  useEffect(() => {
    return () => {
      if (flashTimer.current !== null) window.clearTimeout(flashTimer.current);
    };
  }, []);

  const nameOf = useMemo(() => {
    const map = new Map(nodes.map(n => [n.id, n.label]));
    return (id: string) => map.get(id) ?? id;
  }, [nodes]);

  const matches = useMemo(
    () => (trace ? searchTraceSteps(trace, searchQuery) : []),
    [trace, searchQuery],
  );
  const matchedIds = useMemo(
    () => (searchQuery.trim() ? new Set(matches.map(m => m.id)) : null),
    [matches, searchQuery],
  );

  const toggleStep = useCallback((id: string) => {
    setExpanded(prev => ({ ...prev, [id]: !prev[id] }));
  }, []);

  const locateStep = useCallback((nodeId: string) => {
    // Close the panel and let the canvas pan/zoom + highlight the node.
    onLocateNode(nodeId);
  }, [onLocateNode]);

  const pickSearchResult = useCallback((stepId: string) => {
    setExpanded(prev => ({ ...prev, [stepId]: true }));
    setFlashId(stepId);
    if (flashTimer.current !== null) window.clearTimeout(flashTimer.current);
    flashTimer.current = window.setTimeout(() => setFlashId(null), 1600);
    // Wait a frame so the step is rendered (and not dimmed) before scrolling.
    window.setTimeout(() => {
      stepRefs.current.get(stepId)?.scrollIntoView({ behavior: 'smooth', block: 'center' });
    }, 30);
  }, []);

  const exportTrace = useCallback(() => {
    if (!trace) return;
    const report = buildTraceMarkdown(trace, { projectName });
    const blob = new Blob([report], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'calculation-trace.md';
    a.click();
    URL.revokeObjectURL(url);
  }, [trace, projectName]);

  if (!isOpen) return null;

  const isLarge = trace !== null && trace.steps.length > LARGE_TRACE_THRESHOLD;

  return (
    <ModalWindow
      icon="🔎"
      title="Calculation Trace"
      subtitle={
        trace
          ? `${trace.rootNodeName} — ${trace.steps.length} step${trace.steps.length === 1 ? '' : 's'}`
          : 'Inspect how a result was calculated'
      }
      overlay="rgba(0,0,0,0.7)"
      bg={colors.bg}
      border={colors.border}
      text={colors.text}
      onClose={onClose}
      initialWidth={580}
      initialHeight={660}
      minWidth={400}
      minHeight={360}
      scrollBody={false}
      persistKey="snd.window.calculation-trace"
      footer={
        <div className="px-6 py-3 flex items-center gap-3" style={{ borderTop: `1px solid ${colors.border}` }}>
          <span className="text-[10px] flex-1" style={{ color: colors.label }}>
            Click <span className="font-bold">📍 Locate</span> to jump to a step on the canvas
          </span>
          <button
            onClick={exportTrace}
            disabled={!trace}
            className="px-3 py-1.5 rounded-lg text-xs font-medium transition-all hover:opacity-80 disabled:opacity-40 cursor-pointer"
            style={{ background: 'transparent', color: colors.text, border: `1px solid ${colors.border}` }}
            title="Export the trace as a Markdown document"
          >
            ⬇ Export Trace
          </button>
          <button
            onClick={onClose}
            className="px-4 py-1.5 rounded-lg text-sm font-medium cursor-pointer"
            style={{ background: colors.accent, color: '#fff' }}
          >
            Close
          </button>
        </div>
      }
    >
      {/* Body */}
      <div className="flex-1 min-h-0 flex flex-col">
        {/* Loading (synchronous in practice — defensive state) */}
        {trace === null && error === null && (
          <div className="flex-1 flex items-center justify-center text-sm" style={{ color: colors.label }}>
            Generating calculation trace…
          </div>
        )}

        {/* Error — the original calculation is never affected */}
        {error !== null && (
          <div className="flex-1 flex items-center justify-center p-6">
            <div
              className="max-w-sm w-full rounded-lg p-4 text-sm space-y-2"
              style={{ background: colors.card, border: '1px solid #ef444466' }}
              role="alert"
            >
              <div className="font-bold" style={{ color: '#ef4444' }}>
                ⚠ Unable to generate calculation trace.
              </div>
              <div style={{ color: colors.text }}>
                The original calculation result has not been modified.
              </div>
              <div className="text-xs" style={{ color: colors.label }}>
                Reason: {error}
              </div>
            </div>
          </div>
        )}

        {/* Success */}
        {trace !== null && error === null && (
          <>
            <div className="px-4 pt-3 flex-shrink-0">
              <CalculationTraceHeader trace={trace} colors={colors} />
            </div>

            {/* Controls: search + trace level */}
            <div className="px-4 py-3 flex items-center gap-2 flex-shrink-0">
              <CalculationTraceSearch
                value={searchQuery}
                onChange={setSearchQuery}
                matches={matches}
                total={trace.steps.length}
                onPick={pickSearchResult}
                colors={colors}
                inputRef={el => { searchInputRef.current = el; }}
              />
              <div
                className="flex rounded overflow-hidden flex-shrink-0"
                style={{ border: `1px solid ${colors.border}` }}
                role="group"
                aria-label="Trace level"
              >
                {LEVELS.map(l => (
                  <button
                    key={l.id}
                    onClick={() => setLevel(l.id)}
                    aria-pressed={level === l.id}
                    title={`Show ${l.label.toLowerCase()} level of detail`}
                    className="px-2.5 py-1.5 text-[11px] font-medium transition-colors cursor-pointer"
                    style={{
                      background: level === l.id ? colors.accent : 'transparent',
                      color: level === l.id ? '#fff' : colors.label,
                    }}
                  >
                    {l.label}
                  </button>
                ))}
              </div>
            </div>

            {isLarge && (
              <div
                className="mx-4 mb-2 px-3 py-1.5 rounded text-[11px] flex-shrink-0"
                style={{ color: colors.label, background: colors.card, border: `1px solid ${colors.border}` }}
              >
                Large trace — {trace.steps.length} steps. Use the search field to find a step.
              </div>
            )}

            {/* Steps */}
            <div className="flex-1 min-h-0 overflow-y-auto px-4 pb-4" style={{ scrollbarWidth: 'thin' }}>
              {trace.steps.length === 1 && trace.steps[0].inputs.length === 0 && (
                <div
                  className="rounded-lg p-3 mb-2 text-xs flex-shrink-0"
                  style={{ color: colors.label, background: colors.card, border: `1px solid ${colors.border}` }}
                >
                  This node has no upstream dependencies — it is the start of its calculation chain.
                </div>
              )}
              {trace.steps.map((step, i) => (
                <CalculationTraceStep
                  key={step.id}
                  step={step}
                  index={i}
                  isLast={i === trace.steps.length - 1}
                  level={level}
                  expanded={expanded[step.id] === true}
                  onToggle={() => toggleStep(step.id)}
                  onLocate={() => locateStep(step.nodeId)}
                  nameOf={nameOf}
                  colors={colors}
                  innerRef={el => {
                    if (el) stepRefs.current.set(step.id, el);
                    else stepRefs.current.delete(step.id);
                  }}
                  dimmed={matchedIds !== null && !matchedIds.has(step.id)}
                  flashing={flashId === step.id}
                />
              ))}
            </div>
          </>
        )}
      </div>
    </ModalWindow>
  );
}
